-- INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES (name, code, year, sem, instructor_id);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Biology Laboratory', 'BIO F110', 2020, 2, 206);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('General Biology', 'BIO F111', 2020, 2, 84);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Microbiology', 'BIO F212', 2020, 2, 145);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Biophysics', 'BIO F215', 2020, 2, 139);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Water Sanitation And Solid Wa', 'BIO F216', 2020, 2, 150);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Ecology & Environ Sci', 'BIO F241', 2020, 2, 150);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Genetics', 'BIO F243', 2020, 2, 81);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Instru Methods Of Anal', 'BIO F244', 2020, 2, 45);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'BIO F266', 2020, 2, 208);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Developmental Biology', 'BIO F341', 2020, 2, 208);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Immunology', 'BIO F342', 2020, 2, 80);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'BIO F366', 2020, 2, 208);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'BIO F367', 2020, 2, 208);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'BIO F376', 2020, 2, 208);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'BIO F377', 2020, 2, 208);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Bioprocess Technology', 'BIO F451', 2020, 2, 165);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Stem Cell & Regener Bio', 'BIO G515', 2020, 2, 208);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Adv & Applied Microbio', 'BIO G523', 2020, 2, 70);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Advanced Cell Mole Bio', 'BIO G542', 2020, 2, 117);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Plant Biotechnology', 'BIO G643', 2020, 2, 61);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Nanobiotechnology', 'BIOT F422', 2020, 2, 187);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Independent Study', 'BITS C790T', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Teaching Practice I', 'BITS C791T', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Ph D Seminar', 'BITS C797T', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Ph D Thesis', 'BITS C799T', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Reading Course I', 'BITS E593', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Research Methodology I', 'BITS E661', 2020, 2, 18);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Practice Lect Series I', 'BITS E793T', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Engineering Graphics', 'BITS F110', 2020, 2, 33);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Thermodynamics', 'BITS F111', 2020, 2, 66);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Technical Report Writing', 'BITS F112', 2020, 2, 71);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('General Mathematics II', 'BITS F114', 2020, 2, 2);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Process Engineering', 'BITS F219', 2020, 2, 197);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Environmental Studies', 'BITS F225', 2020, 2, 171);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Multicri De Mak In E & M', 'BITS F313', 2020, 2, 175);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Game Theory And Its Applicatio', 'BITS F314', 2020, 2, 55);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Negotiation Skills And Techniq', 'BITS F319', 2020, 2, 132);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Artificial Intelligence For Ro', 'BITS F327', 2020, 2, 1);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Human Comp Interaction', 'BITS F364', 2020, 2, 51);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Intro To Gender Studies', 'BITS F385', 2020, 2, 28);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Practice School II', 'BITS F412', 2020, 2, 177);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Practice School II', 'BITS F413', 2020, 2, 177);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Introduction To Mems', 'BITS F415', 2020, 2, 151);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Micro-Fluidics & Its App', 'BITS F417', 2020, 2, 158);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Thesis', 'BITS F421T', 2020, 2, 201);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Thesis', 'BITS F422T', 2020, 2, 201);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Thesis', 'BITS F423T', 2020, 2, 201);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Thesis', 'BITS F424T', 2020, 2, 201);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Robotics', 'BITS F441', 2020, 2, 22);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Remote Sens & Image Proc', 'BITS F442', 2020, 2, 82);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Pattern Recognition', 'BITS F446', 2020, 2, 118);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Cryptography', 'BITS F463', 2020, 2, 60);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Machine Learning', 'BITS F464', 2020, 2, 108);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Bioethics & Biosafety', 'BITS F467', 2020, 2, 123);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study In Advanced Topics', 'BITS G513', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Research Project I', 'BITS G529', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Research Project II', 'BITS G539', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Research Practice', 'BITS G540', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Dissertation', 'BITS G562T', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Dissertation', 'BITS G563T', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Dissertation', 'BITS G629T', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Practice School', 'BITS G639', 2020, 2, 177);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Reading Course', 'BITS G649', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Research Methodology I', 'BITS G661', 2020, 2, 207);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Analysis Of Structures', 'CE F241', 2020, 2, 41);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Construction Plan & Tech', 'CE F242', 2020, 2, 201);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Soil Mechanics', 'CE F243', 2020, 2, 11);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Highway Engineering', 'CE F244', 2020, 2, 209);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'CE F266', 2020, 2, 97);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Engineering Hydrology', 'CE F321', 2020, 2, 175);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Water & Wastewater Treat', 'CE F342', 2020, 2, 144);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Des Of Steel Structures', 'CE F343', 2020, 2, 119);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'CE F366', 2020, 2, 10);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'CE F367', 2020, 2, 10);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'CE F376', 2020, 2, 119);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'CE F377', 2020, 2, 119);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Des Of Prest Conc Struct', 'CE F415', 2020, 2, 29);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Comp Appl In Civil Engg', 'CE F416', 2020, 2, 20);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Intro To Bridge Engg', 'CE F420', 2020, 2, 119);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Airport Rail & Waterways', 'CE F425', 2020, 2, 33);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Earthquake Res Des & Con', 'CE F428', 2020, 2, 163);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Structural Dynamics', 'CE F432', 2020, 2, 41);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Introduction To Fem', 'CE F435', 2020, 2, 10);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Special Project', 'CE F491', 2020, 2, 133);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Structural Optimization', 'CE G514', 2020, 2, 201);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Pavement Analysis & Des', 'CE G518', 2020, 2, 172);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Advanced Concrete Technology', 'CE G562', 2020, 2, 20);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Public Transportation', 'CE G566', 2020, 2, 125);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Highway Construction Technolog', 'CE G570', 2020, 2, 172);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Freight Transportation', 'CE G575', 2020, 2, 125);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Adv Concrete Structures', 'CE G613', 2020, 2, 29);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Earthquake Engineering', 'CE G615', 2020, 2, 97);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Adv Foundation Engg', 'CE G620', 2020, 2, 11);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Heat Transfer', 'CHE F241', 2020, 2, 202);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Num Method For Chem Engg', 'CHE F242', 2020, 2, 21);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Material Science & Engg', 'CHE F243', 2020, 2, 52);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Separation Processes I', 'CHE F244', 2020, 2, 159);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'CHE F266', 2020, 2, 67);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Chemical Engg Lab I', 'CHE F312', 2020, 2, 159);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Chemical Engg Lab II', 'CHE F341', 2020, 2, 173);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Process Des Principle II', 'CHE F343', 2020, 2, 112);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'CHE F366', 2020, 2, 3);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'CHE F367', 2020, 2, 3);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'CHE F376', 2020, 2, 3);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'CHE F377', 2020, 2, 3);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Envir Pollution Control', 'CHE F411', 2020, 2, 69);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Colloids And Interface Enginee', 'CHE F498', 2020, 2, 38);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Polymer Technology', 'CHE G522', 2020, 2, 76);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Into To Nano Sci & Tech', 'CHE G528', 2020, 2, 46);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Adv Transport Phenomena', 'CHE G552', 2020, 2, 31);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Computational Fluid Dynamics', 'CHE G554', 2020, 2, 207);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Reaction Engineering', 'CHE G641', 2020, 2, 173);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Chemistry Laboratory', 'CHEM F110', 2020, 2, 40);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('General Chemistry', 'CHEM F111', 2020, 2, 90);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Colloid & Surface Chem', 'CHEM F223', 2020, 2, 138);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Inorganic Chemistry II', 'CHEM F241', 2020, 2, 167);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Chemical Exper I', 'CHEM F242', 2020, 2, 137);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Organic Chemistry II', 'CHEM F243', 2020, 2, 198);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Physical Chemistry III', 'CHEM F244', 2020, 2, 188);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'CHEM F266', 2020, 2, 7);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Instru Methods Of Anal', 'CHEM F313', 2020, 2, 15);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Electrochem Funda & Appl', 'CHEM F327', 2020, 2, 54);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Analytical Chemistry', 'CHEM F329', 2020, 2, 109);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Organic Chem & Drug Des', 'CHEM F335', 2020, 2, 86);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Chemical Exper II', 'CHEM F341', 2020, 2, 30);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Inorganic Chemistry III', 'CHEM F343', 2020, 2, 83);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'CHEM F366', 2020, 2, 30);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'CHEM F367', 2020, 2, 30);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'CHEM F376', 2020, 2, 188);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'CHEM F377', 2020, 2, 188);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Bio & Chemical Sensors', 'CHEM F414', 2020, 2, 179);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Special Project', 'CHEM F491', 2020, 2, 40);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Computer Programming', 'CS F111', 2020, 2, 44);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Data Structures & Algo', 'CS F211', 2020, 2, 203);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Database Systems', 'CS F212', 2020, 2, 141);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Object Oriented Prog', 'CS F213', 2020, 2, 183);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Microproc & Interfacing', 'CS F241', 2020, 2, 146);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'CS F266', 2020, 2, 74);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Computer Networks', 'CS F303', 2020, 2, 51);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Computer Architecture', 'CS F342', 2020, 2, 42);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Compiler Construction', 'CS F363', 2020, 2, 25);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design & Anal Of Algo', 'CS F364', 2020, 2, 199);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'CS F366', 2020, 2, 74);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'CS F367', 2020, 2, 74);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Operating Systems', 'CS F372', 2020, 2, 34);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'CS F376', 2020, 2, 74);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'CS F377', 2020, 2, 74);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Computational Geometry', 'CS F402', 2020, 2, 92);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Artificial Intelligence', 'CS F407', 2020, 2, 44);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Internetworking Tech', 'CS F413', 2020, 2, 194);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Data Mining', 'CS F415', 2020, 2, 89);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Sel Topics From Comp Sc', 'CS F441', 2020, 2, 113);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Special Project', 'CS F491', 2020, 2, 74);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Network Security', 'CS G513', 2020, 2, 136);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Advanced Data Mining', 'CS G520', 2020, 2, 74);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Software For Embedde Sys', 'CS G523', 2020, 2, 176);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Adv Computer Architectur', 'CS G524', 2020, 2, 60);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Cloud Computing', 'CS G527', 2020, 2, 57);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Distributed Data Systems', 'CS G554', 2020, 2, 91);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Tribology', 'DE G513', 2020, 2, 121);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Fracture Mechanics', 'DE G514', 2020, 2, 105);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Electrical Machines', 'ECE F211', 2020, 2, 96);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Microproc & Interfacing', 'ECE F241', 2020, 2, 146);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Microelectronic Circuits', 'ECE F244', 2020, 2, 114);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'ECE F266', 2020, 2, 182);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Communication Systems', 'ECE F311', 2020, 2, 62);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Em Fields & Micro Engg Lab', 'ECE F312', 2020, 2, 168);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Analog Electronics', 'ECE F341', 2020, 2, 120);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'ECE F366', 2020, 2, 114);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'ECE F367', 2020, 2, 114);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'ECE F376', 2020, 2, 77);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'ECE F377', 2020, 2, 77);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Digital Signal Process', 'ECE F434', 2020, 2, 181);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Principles Of Economics', 'ECON F211', 2020, 2, 19);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Funda Of Fin And Account', 'ECON F212', 2020, 2, 103);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Econometric Methods', 'ECON F241', 2020, 2, 35);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Microeconomics', 'ECON F242', 2020, 2, 56);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Macroeconomics', 'ECON F243', 2020, 2, 191);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Economic Of Growth & Dev', 'ECON F244', 2020, 2, 35);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'ECON F266', 2020, 2, 95);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Financial Management', 'ECON F315', 2020, 2, 103);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Public Fin Theo & Policy', 'ECON F341', 2020, 2, 95);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Applied Econometrics', 'ECON F342', 2020, 2, 142);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Economic Anal Of Pub Pol', 'ECON F343', 2020, 2, 55);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Behavioral Economics', 'ECON F345', 2020, 2, 56);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Derivatives & Risk Mgmt', 'ECON F354', 2020, 2, 164);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Buss Anal & Valuation', 'ECON F355', 2020, 2, 106);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'ECON F366', 2020, 2, 95);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'ECON F367', 2020, 2, 95);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'ECON F376', 2020, 2, 95);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'ECON F377', 2020, 2, 95);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Project Appraisal', 'ECON F411', 2020, 2, 191);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Secur Anal & Portfol Mgt', 'ECON F412', 2020, 2, 164);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('New Venture Creation', 'ECON F415', 2020, 2, 132);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('International Business', 'ECON F434', 2020, 2, 19);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Marketing Research', 'ECON F435', 2020, 2, 43);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Electrical Sciences', 'EEE F111', 2020, 2, 174);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Electrical Machines', 'EEE F211', 2020, 2, 96);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Microproc & Interfacing', 'EEE F241', 2020, 2, 146);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Microelectronic Circuits', 'EEE F244', 2020, 2, 114);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Control Systems Laboratory', 'EEE F245', 2020, 2, 14);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Elec & Electronic Circuits Lab', 'EEE F246', 2020, 2, 58);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'EEE F266', 2020, 2, 182);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Communication Systems', 'EEE F311', 2020, 2, 62);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Analog Electronics', 'EEE F341', 2020, 2, 120);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Power Electronics', 'EEE F342', 2020, 2, 185);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'EEE F366', 2020, 2, 114);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'EEE F367', 2020, 2, 114);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'EEE F376', 2020, 2, 77);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'EEE F377', 2020, 2, 77);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Internet Of Things', 'EEE F411', 2020, 2, 149);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Modern Control Systems', 'EEE F422', 2020, 2, 5);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Fibre Optics & Optoelect', 'EEE F426', 2020, 2, 126);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Digital Signal Process', 'EEE F434', 2020, 2, 181);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Antenna Theory And Design', 'EEE F474', 2020, 2, 65);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Modeling Of Field-Effect Nano', 'EEE F477', 2020, 2, 160);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Power Systems Lab', 'EEE F478', 2020, 2, 5);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Rf Microelectronics', 'EEE G510', 2020, 2, 168);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Mobile Personal Communic', 'EEE G592', 2020, 2, 8);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Advanced Digital Communi', 'EEE G622', 2020, 2, 127);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Hardware Software Co-Dsn', 'EEE G626', 2020, 2, 166);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Derivatives & Risk Mgmt', 'FIN F311', 2020, 2, 164);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Secur Anal & Portfol Mgt', 'FIN F313', 2020, 2, 164);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Financial Management', 'FIN F315', 2020, 2, 103);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Financial Risk Analytics & M', 'FIN F414', 2020, 2, 200);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Environ Dev & Climate Ch', 'GS F212', 2020, 2, 36);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Introductory Psychology', 'GS F232', 2020, 2, 154);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Creative Writing', 'GS F241', 2020, 2, 12);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Criti Anal Of Lit & Cine', 'GS F322', 2020, 2, 128);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Public Administration', 'GS F333', 2020, 2, 88);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Intro To Dev Studies', 'HSS F232', 2020, 2, 184);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Introducotry Philosophy', 'HSS F235', 2020, 2, 71);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Symbolic Logic', 'HSS F236', 2020, 2, 124);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Contemporary Indian English Fi', 'HSS F237', 2020, 2, 93);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Crime And New Media', 'HSS F244', 2020, 2, 12);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Gender Science And Technology', 'HSS F245', 2020, 2, 28);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Introduction To Disability Stu', 'HSS F248', 2020, 2, 162);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'HSS F266', 2020, 2, 124);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Intro To Globalization', 'HSS F317', 2020, 2, 184);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Social And Political Ecology', 'HSS F322', 2020, 2, 88);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Cinematic Adaptation', 'HSS F325', 2020, 2, 162);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Human Resource Develop', 'HSS F328', 2020, 2, 196);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Cinematic Art', 'HSS F332', 2020, 2, 170);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Comparative Indian Lit', 'HSS F338', 2020, 2, 128);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Post Colonial Literature', 'HSS F340', 2020, 2, 93);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Disaster And Development', 'HSS F363', 2020, 2, 36);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Science Of Sustainable Happine', 'HSS F365', 2020, 2, 24);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'HSS F376', 2020, 2, 124);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Electrical Machines', 'INSTR F211', 2020, 2, 96);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Microproc & Interfacing', 'INSTR F241', 2020, 2, 146);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Microelectronic Circuits', 'INSTR F244', 2020, 2, 114);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'INSTR F266', 2020, 2, 182);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Electro Inst & Inst Tech', 'INSTR F311', 2020, 2, 77);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Analog Electronics', 'INSTR F341', 2020, 2, 120);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Power Electronics', 'INSTR F342', 2020, 2, 185);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'INSTR F366', 2020, 2, 114);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'INSTR F367', 2020, 2, 114);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'INSTR F376', 2020, 2, 77);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'INSTR F377', 2020, 2, 77);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Virtual Instrumentation', 'INSTR F419', 2020, 2, 135);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Computer Graphics', 'IS F311', 2020, 2, 199);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Software Engineering', 'IS F341', 2020, 2, 101);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Network Programming', 'IS F462', 2020, 2, 113);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Mathematics II', 'MATH F112', 2020, 2, 48);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Probability & Statistics', 'MATH F113', 2020, 2, 107);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Discrete Mathematics', 'MATH F213', 2020, 2, 122);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Number Theory', 'MATH F231', 2020, 2, 143);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Mathematical Methods', 'MATH F241', 2020, 2, 152);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Operations Research', 'MATH F242', 2020, 2, 50);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Graphs And Networks', 'MATH F243', 2020, 2, 94);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Measure & Integration', 'MATH F244', 2020, 2, 78);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'MATH F266', 2020, 2, 13);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Algebra II', 'MATH F314', 2020, 2, 129);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Intro To Functional Anal', 'MATH F341', 2020, 2, 73);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Differential Geometry', 'MATH F342', 2020, 2, 190);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Partial Diff Equations', 'MATH F343', 2020, 2, 63);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Statistical Infer & App', 'MATH F353', 2020, 2, 59);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Complex Analysis', 'MATH F354', 2020, 2, 102);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'MATH F366', 2020, 2, 13);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'MATH F367', 2020, 2, 13);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'MATH F376', 2020, 2, 68);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'MATH F377', 2020, 2, 68);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Combinatorial Maths', 'MATH F421', 2020, 2, 47);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Introduction To Algebraic Topo', 'MATH F423', 2020, 2, 161);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Discrete Maths Struc', 'MATH F441', 2020, 2, 148);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Cosmology', 'MATH F456', 2020, 2, 37);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Nonlinear Optimization', 'MATH F471', 2020, 2, 204);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Workshop Practice', 'ME F110', 2020, 2, 85);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Advanced Mechanics Of Solids', 'ME F218', 2020, 2, 39);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Manufacturing Processes', 'ME F219', 2020, 2, 110);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Heat Transfer', 'ME F220', 2020, 2, 158);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Mechanisms And Machines', 'ME F221', 2020, 2, 211);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Machine Design & Drawing', 'ME F241', 2020, 2, 105);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Ic Engines', 'ME F242', 2020, 2, 79);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Production Techniques I', 'ME F243', 2020, 2, 110);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Kin & Dyn Of Machines', 'ME F244', 2020, 2, 211);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'ME F266', 2020, 2, 98);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Heat Transfer', 'ME F311', 2020, 2, 100);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Production Techniques II', 'ME F313', 2020, 2, 9);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Primemovers & Fluid Mach', 'ME F341', 2020, 2, 72);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Computer Aided Design', 'ME F342', 2020, 2, 177);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Mechanical Vibrations', 'ME F343', 2020, 2, 147);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Engineering Optimization', 'ME F344', 2020, 2, 49);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'ME F366', 2020, 2, 49);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'ME F367', 2020, 2, 49);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'ME F376', 2020, 2, 99);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'ME F377', 2020, 2, 99);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Micro-Fluidics & Its App', 'ME F423', 2020, 2, 158);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Solar Thermal Process En', 'ME F433', 2020, 2, 98);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Composite Material & Des', 'ME F452', 2020, 2, 116);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Refrigeration & Aircond', 'ME F461', 2020, 2, 178);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Combustion', 'ME F482', 2020, 2, 100);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Wind Energy', 'ME F483', 2020, 2, 147);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Automotive Technology', 'ME F484', 2020, 2, 192);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Heating & Cool Of Build', 'ME G513', 2020, 2, 178);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Comput Fluid Dynamics', 'ME G515', 2020, 2, 64);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Convect Heat & Mass Tran', 'ME G534', 2020, 2, 140);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Thermal Equipment Design', 'ME G536', 2020, 2, 153);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Comp Aided Anal & Design', 'ME G611', 2020, 2, 177);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Advanced Vlsi Design', 'MEL G623', 2020, 2, 193);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Analog Ic Design', 'MEL G632', 2020, 2, 156);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Cad For Ic Design', 'MEL G641', 2020, 2, 189);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Vlsi Architecture', 'MEL G642', 2020, 2, 58);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'MF F266', 2020, 2, 98);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Mechatronics & Automat', 'MF F311', 2020, 2, 22);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Casting & Welding', 'MF F343', 2020, 2, 186);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'MF F366', 2020, 2, 49);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'MF F367', 2020, 2, 49);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'MF F376', 2020, 2, 99);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'MF F377', 2020, 2, 99);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Lean Manufacturing', 'MF F418', 2020, 2, 6);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Supply Chain Management', 'MF F421', 2020, 2, 116);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Sustainable Manufacturing', 'MF F485', 2020, 2, 85);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Principles Of Management', 'MGTS F211', 2020, 2, 196);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Materials Processing', 'MST F332', 2020, 2, 16);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Advanced Composites', 'MST G522', 2020, 2, 115);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Dispensing Pharmacy', 'PHA F212', 2020, 2, 53);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Anatomy Physio & Hygiene', 'PHA F214', 2020, 2, 23);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Pharmaceutical Chemistry', 'PHA F241', 2020, 2, 53);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Biological Chemistry', 'PHA F242', 2020, 2, 32);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'PHA F266', 2020, 2, 131);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Instru Methods Of Anal', 'PHA F313', 2020, 2, 26);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Pharmacology II', 'PHA F341', 2020, 2, 111);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Medicinal Chemistry II', 'PHA F342', 2020, 2, 131);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Forensic Pharmacy', 'PHA F343', 2020, 2, 32);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Natural Drugs', 'PHA F344', 2020, 2, 26);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'PHA F366', 2020, 2, 131);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'PHA F367', 2020, 2, 131);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'PHA F376', 2020, 2, 131);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'PHA F377', 2020, 2, 131);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Pharma Mang & Qual Contr', 'PHA F413', 2020, 2, 205);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Biopharmaceutics', 'PHA F414', 2020, 2, 104);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Pathophysiology', 'PHA F415', 2020, 2, 111);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Q A & Regulatory Affairs', 'PHA G532', 2020, 2, 4);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Clinical Research', 'PHA G543', 2020, 2, 23);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Pharmaceutical Bio Statistics', 'PHA G546', 2020, 2, 130);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Pharmaceutical Biotech', 'PHA G613', 2020, 2, 104);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Pharma Admin & Mgmt', 'PHA G616', 2020, 2, 4);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Dosage Form Design', 'PHA G632', 2020, 2, 130);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Physics Laboratory', 'PHY F110', 2020, 2, 134);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Mech Oscillations & Wave', 'PHY F111', 2020, 2, 118);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Elec Magnet & Optics Lab', 'PHY F214', 2020, 2, 180);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Electromagnetic Theo II', 'PHY F241', 2020, 2, 155);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Math Method Of Physics', 'PHY F243', 2020, 2, 180);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Study Project', 'PHY F266', 2020, 2, 195);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Statistical Mechanics', 'PHY F312', 2020, 2, 169);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Theory Of Relativity', 'PHY F315', 2020, 2, 195);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Solid State Physics', 'PHY F341', 2020, 2, 18);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Atomic & Molecular Phy', 'PHY F342', 2020, 2, 17);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Nuclear & Particle Phy', 'PHY F343', 2020, 2, 27);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Advanced Physics Lab', 'PHY F344', 2020, 2, 75);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'PHY F366', 2020, 2, 195);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Laboratory Project', 'PHY F367', 2020, 2, 195);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'PHY F376', 2020, 2, 195);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Design Project', 'PHY F377', 2020, 2, 195);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Thin Film Technology', 'PHY F379', 2020, 2, 210);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Quantum Optics', 'PHY F420', 2020, 2, 87);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Adv Math Methods Of Phy', 'PHY F425', 2020, 2, 134);
INSERT INTO bcms_course(name, code, year, sem, instructor_id) VALUES ('Geometrical Methods In', 'PHY F431', 2020, 2, 157);

